import { StyleSheet } from 'react-native';
import { colors } from './theme';

export const styles = StyleSheet.create({
  addIconWrap: {
    backgroundColor: colors.primary,
    borderColor: 'rgba(6, 37, 26, 0.35)',
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    shadowColor: colors.primary,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    width: 40,
  },
  addTabItem: {
    height: 74,
    justifyContent: 'center',
    paddingBottom: 6,
    paddingTop: 6,
  },
  amountInput: {
    color: colors.text,
    fontSize: 38,
    fontWeight: '800',
    marginBottom: 12,
    paddingVertical: 6,
  },
  amountSmall: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  animatedBody: {
    flex: 1,
  },
  appName: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  avatarImage: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderWidth: 1,
  },
  avatarPicker: {
    alignItems: 'center',
    alignSelf: 'center',
    gap: 10,
    marginVertical: 18,
  },
  avatarPreviewFallback: {
    alignItems: 'center',
    backgroundColor: 'rgba(78, 222, 163, 0.1)',
    borderColor: 'rgba(78, 222, 163, 0.28)',
    borderRadius: 42,
    borderWidth: 1,
    height: 84,
    justifyContent: 'center',
    width: 84,
  },
  avatarPreviewImage: {
    borderColor: 'rgba(78, 222, 163, 0.42)',
    borderRadius: 42,
    borderWidth: 1,
    height: 84,
    width: 84,
  },
  avatarText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  badText: {
    color: colors.expense,
  },
  balance: {
    color: colors.primary,
    fontSize: 34,
    fontWeight: '900',
    marginTop: 8,
  },
  bodyText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  budgetName: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    marginTop: 12,
  },
  card: {
    backgroundColor: 'rgba(20, 30, 52, 0.72)',
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    overflow: 'hidden',
    padding: 14,
  },
  cardAccent: {
    backgroundColor: 'rgba(23, 65, 58, 0.58)',
    borderColor: 'rgba(78, 222, 163, 0.34)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    overflow: 'hidden',
    padding: 14,
  },
  flexCard: {
    flex: 1,
    minWidth: 0,
  },
  cardTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
  },
  cardWarning: {
    backgroundColor: 'rgba(67, 55, 22, 0.66)',
    borderColor: 'rgba(249, 189, 34, 0.42)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    overflow: 'hidden',
    padding: 14,
  },
  categoryBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(78, 222, 163, 0.1)',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  categoryBadgeCompact: {
    flexShrink: 1,
    gap: 5,
    maxWidth: 82,
    paddingHorizontal: 7,
    paddingVertical: 7,
  },
  categoryBadgeText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  categoryBadgeTextCompact: {
    flexShrink: 1,
    fontSize: 12,
  },
  categoryList: {
    gap: 12,
    marginTop: 18,
  },
  chipRow: {
    gap: 10,
    paddingBottom: 14,
  },
  createBudgetCard: {
    alignItems: 'center',
    borderColor: 'rgba(218, 226, 253, 0.18)',
    borderRadius: 18,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    gap: 10,
    marginBottom: 120,
    padding: 22,
  },
  createBudgetText: {
    color: colors.muted,
    fontSize: 17,
    fontWeight: '700',
  },
  dashboardActionRow: {
    marginTop: 14,
  },
  dashboardSpendingAmount: {
    color: colors.text,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 82,
    minWidth: 56,
    textAlign: 'right',
  },
  dashboardSpendingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  donutAmount: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
    width: 104,
  },
  donutCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    width: 112,
  },
  donutWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 16,
  },
  dropdownButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(9, 18, 35, 0.46)',
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  dropdownGrid: {
    gap: 12,
    marginTop: 14,
  },
  dropdownLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  dropdownMenuCard: {
    backgroundColor: '#121c31',
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    maxHeight: '78%',
    padding: 18,
    width: '100%',
  },
  dropdownOption: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  dropdownOptionActive: {
    backgroundColor: 'rgba(78, 222, 163, 0.14)',
    borderColor: 'rgba(78, 222, 163, 0.5)',
  },
  dropdownOptionList: {
    gap: 10,
    marginTop: 18,
  },
  dropdownOptionText: {
    color: colors.muted,
    fontSize: 15,
    fontWeight: '800',
  },
  dropdownOptionTextActive: {
    color: colors.primary,
  },
  dropdownValue: {
    color: colors.text,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  dropdownWrap: {
    width: '100%',
  },
  editedText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  editHint: {
    color: colors.soft,
    fontSize: 12,
    marginTop: 4,
  },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 30,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  goodText: {
    color: colors.primary,
  },
  header: {
    alignItems: 'flex-start',
    borderBottomColor: 'rgba(218, 226, 253, 0.08)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 12,
    paddingHorizontal: 16,
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(20, 30, 52, 0.8)',
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    position: 'relative',
    width: 44,
  },
  iconButtonActive: {
    borderColor: colors.primary,
  },
  inlineIconButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(78, 222, 163, 0.1)',
    borderColor: 'rgba(78, 222, 163, 0.34)',
    borderRadius: 15,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  infoButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(78, 222, 163, 0.1)',
    borderColor: 'rgba(78, 222, 163, 0.34)',
    borderRadius: 14,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  inputLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 12,
    textTransform: 'uppercase',
  },
  kicker: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  linkText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  loadingText: {
    color: colors.muted,
    marginTop: 8,
  },
  loadingTitle: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '900',
    marginTop: 12,
  },
  loadingWrap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  miniStat: {
    backgroundColor: 'rgba(9, 18, 35, 0.44)',
    borderColor: 'rgba(218, 226, 253, 0.08)',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    padding: 12,
  },
  miniStatValue: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 8,
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#121c31',
    borderColor: colors.border,
    borderRadius: 26,
    borderWidth: 1,
    padding: 20,
    width: '100%',
  },
  modalTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
  },
  mutedText: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 8,
  },
  notificationBadge: {
    alignItems: 'center',
    backgroundColor: colors.warning,
    borderColor: '#07111f',
    borderRadius: 11,
    borderWidth: 2,
    elevation: 5,
    minWidth: 21,
    paddingHorizontal: 5,
    position: 'absolute',
    right: -7,
    shadowColor: '#000',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.26,
    shadowRadius: 8,
    top: -7,
    zIndex: 3,
  },
  notificationBadgeText: {
    color: '#201700',
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 15,
  },
  notificationContent: {
    flex: 1,
    minWidth: 0,
  },
  notificationItem: {
    alignItems: 'flex-start',
    backgroundColor: 'rgba(218, 226, 253, 0.06)',
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  notificationItemUrgent: {
    backgroundColor: 'rgba(67, 55, 22, 0.66)',
    borderColor: 'rgba(249, 189, 34, 0.42)',
  },
  notificationList: {
    gap: 10,
    marginBottom: 16,
    marginTop: 14,
  },
  notificationMessage: {
    marginTop: 14,
  },
  notificationTitle: {
    color: colors.text,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  notificationStatusDot: {
    backgroundColor: colors.primary,
    borderRadius: 5,
    height: 10,
    marginTop: 5,
    width: 10,
  },
  notificationStatusDotUrgent: {
    backgroundColor: colors.warning,
  },
  percentText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  pill: {
    alignItems: 'center',
    backgroundColor: 'rgba(218, 226, 253, 0.08)',
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1.5,
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 8,
    minHeight: 46,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  pillActive: {
    backgroundColor: 'rgba(78, 222, 163, 0.16)',
    borderColor: 'rgba(78, 222, 163, 0.58)',
  },
  pillDanger: {
    backgroundColor: 'rgba(255, 179, 176, 0.12)',
    borderColor: 'rgba(255, 179, 176, 0.4)',
  },
  pillText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  pillTextActive: {
    color: colors.primary,
  },
  pillTextDanger: {
    color: colors.expense,
  },
  pressed: {
    opacity: 0.76,
    transform: [{ scale: 0.98 }],
  },
  profileInlineField: {
    flex: 1,
    minWidth: 0,
  },
  profileInlineInputs: {
    flexDirection: 'row',
    gap: 12,
  },
  profileModalScroll: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 24,
    width: '100%',
  },
  profileSaveButtonWrap: {
    marginTop: 18,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 18,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 18,
  },
  primaryButtonDisabled: {
    backgroundColor: '#445063',
  },
  primaryButtonText: {
    color: '#06251a',
    fontSize: 16,
    fontWeight: '900',
  },
  progressFill: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: 8,
  },
  progressTrack: {
    backgroundColor: 'rgba(218, 226, 253, 0.13)',
    borderRadius: 999,
    height: 8,
    marginTop: 16,
    overflow: 'hidden',
  },
  progressWarning: {
    backgroundColor: colors.warning,
  },
  reportExportHint: {
    marginBottom: 14,
    marginTop: 8,
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rowSmall: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  safe: {
    flex: 1,
  },
  screenTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 180,
  },
  searchBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    borderRadius: 24,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    paddingHorizontal: 18,
  },
  searchInput: {
    color: '#172033',
    flex: 1,
    fontSize: 16,
    minHeight: 58,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 10,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 21,
    fontWeight: '900',
  },
  segment: {
    backgroundColor: 'rgba(20, 30, 52, 0.78)',
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
    padding: 7,
  },
  segmentItem: {
    alignItems: 'center',
    borderRadius: 14,
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  segmentItemActive: {
    backgroundColor: 'rgba(78, 222, 163, 0.2)',
  },
  segmentText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: colors.primary,
  },
  shell: {
    flex: 1,
  },
  sideStack: {
    flex: 1,
    gap: 12,
  },
  sideValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 8,
  },
  statRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 18,
  },
  subtitle: {
    color: colors.muted,
    fontSize: 14,
    marginTop: 4,
  },
  tabBar: {
    backgroundColor: 'rgba(13, 21, 38, 0.96)',
    borderColor: 'rgba(218, 226, 253, 0.12)',
    borderRadius: 22,
    borderTopWidth: 1,
    bottom: 12,
    height: 84,
    left: 12,
    paddingBottom: 12,
    paddingTop: 10,
    position: 'absolute',
    right: 12,
  },
  tabBarIconSlot: {
    marginBottom: 4,
    marginTop: 2,
  },
  tabIconWrap: {
    alignItems: 'center',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 48,
  },
  tabIconWrapActive: {
    backgroundColor: 'rgba(78, 222, 163, 0.16)',
  },
  tabItem: {
    height: 74,
    justifyContent: 'center',
    paddingBottom: 6,
    paddingTop: 6,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 13,
    marginTop: 2,
  },
  textInput: {
    backgroundColor: 'rgba(9, 18, 35, 0.46)',
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    color: colors.text,
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  tourActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginTop: 20,
  },
  tourCard: {
    backgroundColor: '#121c31',
    borderColor: 'rgba(78, 222, 163, 0.36)',
    borderRadius: 26,
    borderWidth: 1,
    bottom: 28,
    left: 20,
    padding: 20,
    position: 'absolute',
    right: 20,
  },
  tourOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.48)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  tourSecondary: {
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    minHeight: 54,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  tourSecondaryText: {
    color: colors.muted,
    fontSize: 16,
    fontWeight: '800',
  },
  tourSpotlight: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(18, 28, 49, 0.9)',
    borderColor: colors.primary,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginTop: 95,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  tourSpotlightText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  tourTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 8,
    marginTop: 8,
  },
  transactionAmount: {
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  transactionAmountWrap: {
    alignItems: 'flex-end',
    flex: 0.82,
  },
  transactionIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(218, 226, 253, 0.08)',
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  transactionMeta: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 4,
  },
  transactionMiddle: {
    flex: 1,
  },
  transactionRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(218, 226, 253, 0.08)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  transactionTime: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 4,
  },
  transactionDate: {
    color: colors.soft,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
    textAlign: 'right',
  },
  transactionTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  titleWithInfo: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 8,
  },
  twoColumn: {
    flexDirection: 'row',
    gap: 12,
  },
  warningText: {
    color: colors.warning,
  },
  wrapRow: {
    columnGap: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
    marginTop: 14,
    rowGap: 10,
  },
});
